// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20220915194941_DummySeeding")]
    partial class DummySeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Some brand",
                            Description = "This is a full description for product 1",
                            Name = "Product 1",
                            PictureUrl = "",
                            Price = 100L,
                            QuantityInStock = 1,
                            Type = "A type"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Some brand",
                            Description = "This is a full description for product 2",
                            Name = "Product 2",
                            PictureUrl = "",
                            Price = 200L,
                            QuantityInStock = 2,
                            Type = "A type"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Some brand",
                            Description = "This is a full description for product 3",
                            Name = "Product 3",
                            PictureUrl = "",
                            Price = 300L,
                            QuantityInStock = 3,
                            Type = "A type"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Some brand",
                            Description = "This is a full description for product 4",
                            Name = "Product 4",
                            PictureUrl = "",
                            Price = 400L,
                            QuantityInStock = 4,
                            Type = "A type"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Some brand",
                            Description = "This is a full description for product 5",
                            Name = "Product 5",
                            PictureUrl = "",
                            Price = 500L,
                            QuantityInStock = 5,
                            Type = "A type"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Some brand",
                            Description = "This is a full description for product 6",
                            Name = "Product 6",
                            PictureUrl = "",
                            Price = 600L,
                            QuantityInStock = 6,
                            Type = "A type"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Some brand",
                            Description = "This is a full description for product 7",
                            Name = "Product 7",
                            PictureUrl = "",
                            Price = 700L,
                            QuantityInStock = 7,
                            Type = "A type"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Some brand",
                            Description = "This is a full description for product 8",
                            Name = "Product 8",
                            PictureUrl = "",
                            Price = 800L,
                            QuantityInStock = 8,
                            Type = "A type"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Some brand",
                            Description = "This is a full description for product 9",
                            Name = "Product 9",
                            PictureUrl = "",
                            Price = 900L,
                            QuantityInStock = 9,
                            Type = "A type"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Some brand",
                            Description = "This is a full description for product 10",
                            Name = "Product 10",
                            PictureUrl = "",
                            Price = 1000L,
                            QuantityInStock = 10,
                            Type = "A type"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Some brand",
                            Description = "This is a full description for product 11",
                            Name = "Product 11",
                            PictureUrl = "",
                            Price = 1100L,
                            QuantityInStock = 11,
                            Type = "A type"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Some brand",
                            Description = "This is a full description for product 12",
                            Name = "Product 12",
                            PictureUrl = "",
                            Price = 1200L,
                            QuantityInStock = 12,
                            Type = "A type"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Some brand",
                            Description = "This is a full description for product 13",
                            Name = "Product 13",
                            PictureUrl = "",
                            Price = 1300L,
                            QuantityInStock = 13,
                            Type = "A type"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Some brand",
                            Description = "This is a full description for product 14",
                            Name = "Product 14",
                            PictureUrl = "",
                            Price = 1400L,
                            QuantityInStock = 14,
                            Type = "A type"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Some brand",
                            Description = "This is a full description for product 15",
                            Name = "Product 15",
                            PictureUrl = "",
                            Price = 1500L,
                            QuantityInStock = 15,
                            Type = "A type"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Some brand",
                            Description = "This is a full description for product 16",
                            Name = "Product 16",
                            PictureUrl = "",
                            Price = 1600L,
                            QuantityInStock = 16,
                            Type = "A type"
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Some brand",
                            Description = "This is a full description for product 17",
                            Name = "Product 17",
                            PictureUrl = "",
                            Price = 1700L,
                            QuantityInStock = 17,
                            Type = "A type"
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Some brand",
                            Description = "This is a full description for product 18",
                            Name = "Product 18",
                            PictureUrl = "",
                            Price = 1800L,
                            QuantityInStock = 18,
                            Type = "A type"
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Some brand",
                            Description = "This is a full description for product 19",
                            Name = "Product 19",
                            PictureUrl = "",
                            Price = 1900L,
                            QuantityInStock = 19,
                            Type = "A type"
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Some brand",
                            Description = "This is a full description for product 20",
                            Name = "Product 20",
                            PictureUrl = "",
                            Price = 2000L,
                            QuantityInStock = 20,
                            Type = "A type"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
